### ISSUE TITLE
User database

### ISSUE THREAD

**Issue by Joshrlear** [Joshrlear/Sprynamics#108]
Need something like a user database, so that I can see and search all current users.

**Comment by hermbit** [comment]
This already exists in firebase: 
![image](https://user-images.githubusercontent.com/28285686/36381587-11020ec2-1554-11e8-92a5-92c30f9150ab.png)

It has a ton of built-in features so it would make the most sense to use that, rather than reinventing the wheel.

You can access it from the Firebase Console, if you go to https://console.firebase.google.com, open the Sprynamics project and go to the "Authentication" tab.

**Comment by Joshrlear** [comment]
oh perfect! how do I login to firebase?

*- Josh Lear*
*  Owner, Express RE Marketing*
*  619-507-6807*
  *Website <https://sites.google.com/view/expressremarketing/home> -
Facebook <https://www.facebook.com/expressREmarketing/>*

<https://sites.google.com/view/expressremarketing/automation>
<https://sites.google.com/view/expressremarketing/designs>
<https://sites.google.com/view/expressremarketing/home>
<https://sites.google.com/view/expressremarketing/home>

*Pricing and Project Timeline Disclaimer:*
Express RE Marketing project timeline has a *14 day deadline, *timeline
starts only after receiving the required information.* Any additional time
required will accrue a fee of $5.00/day. *
All "Template Projects" have a *Flat Fee of $15.00*. *Any changes required
on a Template Project will result in an upgrade to Custom Project pricing. *
All "Custom Projects" are subject to custom pricing. Custom Projects
include two free drafts, with a maximum of three changes per draft, drafts
unlimited.
Please submit all changes at the beginning of the day to allow a turnaround
time of 24 hours.
Print and mail set up is a *complimentary* service provided by Express RE
Marketing. We are *not responsible* for any undelivered mail or printing
and cutting issues.
Prior to receiving a final draft and/or having your final draft sent to
print and mail you must pay the invoice in full.
