### ISSUE TITLE
Initial page load problem

### ISSUE THREAD

**Issue by Joshrlear** [Joshrlear/Sprynamics#11]
When going to the url sprynamics.com (I think on both mobile and desktop) it takes me to a blank page with the nav bar at the top and thats it. I then either click: refresh, the logo, or any of the nav bar links and the website actually loads properly.

**Comment by hermbit** [comment]
Hmm.. I'm not seeing this issue on mobile nor on desktop. 
This may have something to do with your browser cache, can you try clearing your cache (from "delete browsing history" menu) and loading again?

**Comment by Joshrlear** [comment]
I did that and it seems to have fixed it but I am concerned that my users wont know or care to clear their cache like this and that they will see a blank page then just leave ...most likely they will refresh or something but it's still concerning. Is there anyway to fix this so that people don't have to clear their cache and history?

**Comment by royceshayegan** [comment]
This only happens during the stages of development. Because you have kept tabs on the site, opening it several times while the site was either down, unfinished, or updates were occurring, files for the website have been cached and eventually caused that error when certain files you had stored were in conflict with each other.

In other words "cache" is simply saving the files of the website so they can be used later more quickly instead of downloading them from the server over and over.

This would never happen to a new user since they didn't open the site while it was unfinished or bugged.

Not only that, but caching only lasts for a certain period of time, after which they're removed regardless of whether the user wants to keep them or not.

**Comment by hermbit** [comment]
Closing this since it was just a cache issue from viewing the site during development.

**Comment by Joshrlear** [comment]
Alright, cool! thanks for clearing that up
