### ISSUE TITLE
Another text feature

### ISSUE THREAD

**Issue by Joshrlear** [Joshrlear/Sprynamics#50]
Allow text to rotate, tilt, fold and bend.

**Comment by hermbit** [comment]
Text can currently be rotated and skewed. 
Folding and bending require much more complicated algorithms to achieve, especially in real-time in a web browser. 
Since this is a "maybe," for the purposes of time and focus I'll close it for now and we can discuss once we have the main features completed.

**Comment by Joshrlear** [comment]
Okay, thanks for looking into it

On Jan 25, 2018 12:28 AM, "Michael Auderer" <notifications@github.com>
wrote:

Closed #50 <https://github.com/Joshrlear/Sprynamics/issues/50>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Joshrlear/Sprynamics/issues/50#event-1440955661>, or mute
the thread
