### ISSUE TITLE
Wrap text

### ISSUE THREAD

**Issue by Joshrlear** [Joshrlear/Sprynamics#59]
Need a text wrap option like on publisher (ability to wrap text around objects and pictures).

**Comment by hermbit** [comment]
This is a very, very tricky one. This requires some very complex text rendering that isn't natively supported in canvas. Its somehow achievable, because Publisher does it, but in this case you can leverage the single line "text" elements and the width-handles on the "paragraph" elements. If you drag the width handles on the paragraphs, you can achieve some manual wrapping.

I checked out Canva, and even they don't have this feature. They have a tutorial that includes "text wrapping" but its using the strategy I just described, which we can already do with Sprynamics so far.

Here's the Canva tutorial I'm talking about: https://www.canva.com/design/DAAuzcM0FY0/remix?minichallenge

**Comment by Joshrlear** [comment]
Okay, we can make this work.
